joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 500

eff_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: &robot_joints
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_elbow_joint
    - l_wrist_1_joint
    - l_wrist_2_joint
    - l_wrist_3_joint
  gains: # Required because we're controlling an effort interface
    l_shoulder_pan_joint: {p: 4000,  d: 200, i: 1, i_clamp: 1}
    l_shoulder_lift_joint: {p: 10000,  d: 200, i: 1, i_clamp: 1}
    l_elbow_joint: {p: 2000,  d: 20, i: 1, i_clamp: 1}
    l_wrist_1_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    l_wrist_2_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    l_wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    l_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    l_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    l_elbow_joint: {trajectory: 0.1, goal: 0.1}
    l_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    l_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    l_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

joint_group_eff_controller:
  type: effort_controllers/JointGroupEffortController
  joints: *robot_joints

scaled_pos_joint_traj_controller:
   type: position_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      l_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      l_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      l_elbow_joint: {trajectory: 0.2, goal: 0.1}
      l_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      l_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      l_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

pos_joint_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      l_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      l_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      l_elbow_joint: {trajectory: 0.2, goal: 0.1}
      l_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      l_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      l_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20