right_robot:     #给控制器加类名
  # Settings for ros_control control loop
  hardware_control_loop:
    loop_hz: &loop_hz 300

  # Settings for ros_control hardware interface
  ur_hardware_interface:
    joints: &robot_joints
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint

  # Publish all joint states ----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: *loop_hz

  # Publish wrench ----------------------------------
  force_torque_sensor_controller:
    type: force_torque_sensor_controller/ForceTorqueSensorController
    publish_rate: *loop_hz

  # Publish speed_scaling factor
  speed_scaling_state_controller:
    type: scaled_controllers/SpeedScalingStateController
    publish_rate: *loop_hz

  # Joint Trajectory Controller - position based -------------------------------
  # For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
  scaled_pos_joint_traj_controller:
    type: position_controllers/ScaledJointTrajectoryController
    joints: *robot_joints
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      right_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      right_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    stop_trajectory_duration: 0.5
    state_publish_rate: *loop_hz
    action_monitor_rate: 20

  pos_joint_traj_controller:
    type: position_controllers/JointTrajectoryController
    joints: *robot_joints
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      right_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      right_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    stop_trajectory_duration: 0.5
    state_publish_rate: *loop_hz
    action_monitor_rate: 20

  scaled_vel_joint_traj_controller:
    type: velocity_controllers/ScaledJointTrajectoryController
    joints: *robot_joints
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_shoulder_pan_joint: { trajectory: 0.1, goal: 0.1 }
      right_shoulder_lift_joint: { trajectory: 0.1, goal: 0.1 }
      right_elbow_joint: { trajectory: 0.1, goal: 0.1 }
      right_wrist_1_joint: { trajectory: 0.1, goal: 0.1 }
      right_wrist_2_joint: { trajectory: 0.1, goal: 0.1 }
      right_wrist_3_joint: { trajectory: 0.1, goal: 0.1 }
    gains:
      #!!These values have not been optimized!!
      right_shoulder_pan_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_shoulder_lift_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_elbow_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_wrist_1_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_wrist_2_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_wrist_3_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
    # Use a feedforward term to reduce the size of PID gains
    velocity_ff:
      right_shoulder_pan_joint: 1.0
      right_shoulder_lift_joint: 1.0
      right_elbow_joint: 1.0
      right_wrist_1_joint: 1.0
      right_wrist_2_joint: 1.0
      right_wrist_3_joint: 1.0
    stop_trajectory_duration: 0.5
    state_publish_rate: *loop_hz
    action_monitor_rate: 20

  vel_joint_traj_controller:
    type: velocity_controllers/JointTrajectoryController
    joints: *robot_joints
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_shoulder_pan_joint: { trajectory: 0.1, goal: 0.1 }
      right_shoulder_lift_joint: { trajectory: 0.1, goal: 0.1 }
      right_elbow_joint: { trajectory: 0.1, goal: 0.1 }
      right_wrist_1_joint: { trajectory: 0.1, goal: 0.1 }
      right_wrist_2_joint: { trajectory: 0.1, goal: 0.1 }
      right_wrist_3_joint: { trajectory: 0.1, goal: 0.1 }
    gains:
      #!!These values have not been optimized!!
      right_shoulder_pan_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_shoulder_lift_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_elbow_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_wrist_1_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_wrist_2_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
      right_wrist_3_joint: { p: 5.0, i: 0.05, d: 0.1, i_clamp: 1 }
    # Use a feedforward term to reduce the size of PID gains
    velocity_ff:
      right_shoulder_pan_joint: 1.0
      right_shoulder_lift_joint: 1.0
      right_elbow_joint: 1.0
      right_wrist_1_joint: 1.0
      right_wrist_2_joint: 1.0
      right_wrist_3_joint: 1.0
    stop_trajectory_duration: 0.5
    state_publish_rate: *loop_hz
    action_monitor_rate: 20

  # Pass an array of joint velocities directly to the joints
  joint_group_vel_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints: *robot_joints

  forward_joint_traj_controller:
    type: "pass_through_controllers/JointTrajectoryController"
    joints: *robot_joints

  forward_cartesian_traj_controller:
    type: "pass_through_controllers/CartesianTrajectoryController"
    joints: *robot_joints

  twist_controller:
    type: "ros_controllers_cartesian/TwistController"
    base_frame_id: "right_base"
    frame_id: "right_tool0_controller"
    publish_rate: *loop_hz
    joints: *robot_joints

  pose_based_cartesian_traj_controller:
    type: pose_controllers/CartesianTrajectoryController

    # UR driver convention
    base: right_base
    tip: right_tool0_controller
    joints: *robot_joints

  joint_based_cartesian_traj_controller:
    type: position_controllers/CartesianTrajectoryController

    # UR driver convention
    base: right_base
    tip: right_tool0
    joints: *robot_joints

  robot_status_controller:
    type: industrial_robot_status_controller/IndustrialRobotStatusController
    handle_name: industrial_robot_status_handle
    publish_rate: 10

  joint_to_cartesian_controller:
    type: "cartesian_controllers/JointControllerAdapter"
    end_effector_link: "right_tool0"
    robot_base_link: "right_base_link"
    target_frame_topic: "target_frame"
    joints: *robot_joints

    joint_limits:
      right_shoulder_pan_joint:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      right_shoulder_lift_joint:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      right_elbow_joint:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      right_wrist_1_joint:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0
      right_wrist_2_joint:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0
      right_wrist_3_joint:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0

  joint_to_cartesian_controller/joint_traj_controller:
    type: position_controllers/JointTrajectoryController
    joints: *robot_joints
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      right_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      right_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    stop_trajectory_duration: 0.5
    state_publish_rate: *loop_hz
    action_monitor_rate: 20

  selfdefined_trajectory_controller:
    type: position_controllers/SelfDefinedTrajectoryController
    joints: *robot_joints
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      right_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      right_elbow_joint: {trajectory: 0.2, goal: 0.1}
      right_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      right_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      right_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate: *loop_hz
    action_monitor_rate: 20
    topic_target_wrench: "/right_robot/target_wrench"
    # topic_current_wrench: "/right_robot/robotiq_current_wrench"
    topic_current_wrench: "/right_robot/ur5e_current_wrench"
    topic_currel_errorpose: "/right_robot/error_pos_otherToself"
    compliance_link: "right_tool0"
    verbose: true
    tra_velmax: 1.0
    rot_velmax: 1.57
    tra_accmax: 10
    rot_accmax: 10
    wrench_dead: 
      - 1.0
      - 1.0
      - 1.0
      - 0.01
      - 0.01
      - 0.01
  