controller_list:
  - name: fake_left_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_right_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_left_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_dh_base_finger1_joint
  - name: fake_right_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - right_dh_base_finger1_joint
  - name: fake_dual_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
initial:  # Define initial robot poses per group
  - group: dual_robot
    pose: home